feat: add mongoose schemas and CRUD operation API endpoints
OctoPipeline/octopipeline pull request #13
Opened 2021-10-22 18:43 UTC by harshasrikara

### Summary
Added mongoose schemas, validate that it works & add CRUD operations to work with Users and Requests

### Testing
 - Comment out the NextJS service in the `docker-compose.yml` file
 - Launch MongoDB & other services through `docker-compose up`
 - Run `npm install` to pick up new dependencies
 - Start the NextJS application in development mode with `npm run dev`

Be able to open up `http://localhost:3000` and see the NextJS UI.

 - Make an API POST Request to `http://localhost:3000/api/user` with the following payload

```
{
    "name": "<Insert your name>",
    "email": "<Insert your email>",
    "admin": true
}
```

 - Expect response in the following format

```
{"name":"Harsha Bob","email":"srikaraharsha@gmail.com","admin":true,"_id":"6173027ed2263e8b5298fec7","__v":0}
```

 - Make an API GET Request to `http://localhost:3000/api/user`

Expect a response in the following format

```
[
    {
        "_id": "617302028846a934ef24b670",
        "name": "Harsha Srikara",
        "email": "harshasrikara@gmail.com",
        "admin": true,
        "__v": 0
    },
    {
        "_id": "6173027ed2263e8b5298fec7",
        "name": "Harsha Bob",
        "email": "srikaraharsha@gmail.com",
        "admin": true,
        "__v": 0
    }
]
```

 - Also verify that the data was successfully saved in MongoDB by opening up the Mongo Express page on `http://localhost:8081` or connecting to the Mongo Instance via Mongo Compass / Mongod.

### Endpoints added

 - GET `/api` - debugging
 - GET `/api/user`
 - POST `/api/user`
 - GET `/api/user/[user_id]`
 - PUT `/api/user/[user_id]`
 - DELETE `/api/user/[user_id]`
 - GET `/api/request`
 - POST `/api/request`
 - GET `/api/user/[request_id]`
 - PUT `/api/user/[request_id]`
 - DELETE `/api/user/[request_id]`

### Schemas

 - User
```
export interface IUser extends Document {
  name: string;
  email: string;
  admin: boolean;
}
```

 - Request
```
export enum status {
  SUBMITTED = "SUBMITTED",
  APPROVED = "APPROVED",
  PRINTING = "PRINTING",
}

export interface IRequest extends Document {
  status: status;
  gcode: string;
  owner: Pick<IUser, "email">;
  approver: Pick<IUser, "email">;
}
```

### Additional Context
Currently, the Mongo URI is hard coded in the next js application to connect over localhost. This was done to accelerate local development since the docker setup right now is designed only for production. In the future we will connect to the mongo instance over `mongo:27017` instead of `localhost:27017` and only expose the database within the docker network. 

Closes #11 & Closes #12

2021-10-22 19:57 UTC, sanjeevpenupala commented on pages/api/user/index.ts
> +      const db = await connectToDatabase(); // connect to database
Delete

2021-10-22 19:57 UTC, sanjeevpenupala commented on pages/api/user/index.ts
> +      const db = await connectToDatabase(); // connect to database
Delete

2021-10-22 20:01 UTC, aemmadi commented on pages/api/user/index.ts
> +  };
Please document the `ApiFunc` logic you used in this block

2021-10-22 20:01 UTC, aemmadi commented on pages/api/user/[id].ts
> +  };
Please document the `ApiFunc` approach

2021-10-22 20:01 UTC, aemmadi commented on util/dbConnect.ts
> +// process.env.MONGODB_URI
`// TODO: replace URI with process.env.MONGODB_URI`

2021-10-22 20:13 UTC, sanjeevpenupala requested changes
Change all import paths from implicit to explicit

2021-10-22 20:34 UTC, aemmadi requested changes
Take a look at the comments.

2021-10-22 20:34 UTC, aemmadi commented on util/models/Request.ts
> +  mongoose.models.RequestSchema || model("Request", RequestSchema);
`// TODO: Fix the starting bug where overwriting the user model errors out.`

Had to re-run the code to get the model working. Fix it so that it works without the initial push it manually needs.

2021-11-03 23:14 UTC, harshasrikara commented
> Change all import paths from implicit to explicit

Closes #16

2021-11-05 19:21 UTC, aemmadi requested changes
Still need a few minor tweaks

2021-11-05 19:21 UTC, aemmadi commented on pages/api/request/index.ts
> +import ApiFuncs from "../../../util/functions";
Change to absolute paths

2021-11-05 19:21 UTC, aemmadi commented on util/models/User.ts
> +  mongoose.models.UserSchema || model("User", UserSchema);
If this is fixed, remove comment

2021-11-05 19:21 UTC, aemmadi commented on util/models/Request.ts
> +  mongoose.models.RequestSchema || model("Request", RequestSchema);
If this is fixed, remove comment

2021-11-05 19:21 UTC, aemmadi commented on util/dbConnect.ts
> +const MONGODB_URI = "mongodb://root:example@localhost:27017/";
Might want to replace the hardcode to the `env` variable

2021-11-05 19:23 UTC, harshasrikara commented on util/dbConnect.ts
> +const MONGODB_URI = "mongodb://root:example@localhost:27017/";
Still a TODO

2021-11-05 19:23 UTC, harshasrikara commented on util/models/Request.ts
> +  mongoose.models.RequestSchema || model("Request", RequestSchema);
Still a TODO

2021-11-05 19:23 UTC, harshasrikara commented on util/models/User.ts
> +  mongoose.models.UserSchema || model("User", UserSchema);
Still a TODO

2021-11-05 19:26 UTC, aemmadi approved these changes
LGTM!

2021-11-05 19:26 UTC, spenpal2000 approved these changes
Looks good to me!

2021-11-05 19:26 UTC, merged